#!/bin/bash
#
# bye-reader start script
#
# chkconfig: 345 99 1
# description: uwsgi start script
# processname: uwsgi
# pidfile: /tmp/uwsgi.pid
#

# Source function library.
. /lib/lsb/init-functions

PROGNAME="uwsgi"
PID="/var/lock/subdys/$PROGNAME.pid"
LOCK="/var/lock/subdys/$PROGNAME.lock"
RETVAL=0

UWSGI_BIN="/home/vagrant/.pyenv/shims/uwsgi"
UWSGI_APP_BIN="/home/myproject"
UWSGI_LOG="/home/myproject/log/$PROGNAME.log"
UWSGI_APP_INIT="/home/myproject/uwsgi.ini"

PROG=$UWSGI_BIN
SSD="/sbin/start-stop-daemon"

[ -f $PROG ] || exit 0

start() {
        mkdir /var/lock/subdys/
        touch /var/lock/subdys/uwsgi.log
        echo -n "Starting $PROGNAME: "
        $SSD --start --quiet --background --retry 5 --oknodo --exec $PROG $UWSGI_APP_INIT -- --pidfile $PID
        echo
        [ $RETVAL = 0 ] && touch $LOCK
        return $RETVAL
}

stop() {
        echo -n "Stopping $PROGNAME: "
        killproc -p $PID $PROGNAME -INT
        RETVAL=$?
        echo
        [ $RETVAL = 0 ] && rm -f $LOCK $PID
}

show_status() {
        status $PROGNAME
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    status)
        show_status
        ;;
    *)
        echo "Usage: $PROGNAME {start|stop|restart|status}"
        RETVAL=2
        ;;
esac
exit $RETVAL
